$power = $HOME/.config/hypr/hyprland/scripts/power.sh

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = $power lock
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = $power lock
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = $power suspend
}
